# Generated by Django 5.1.7 on 2025-03-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='grocery_images/'),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
